# Generated by Django 4.2 on 2023-04-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=232, null=True)),
                ('roll', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=232, null=True)),
            ],
        ),
    ]
